src_files:
  - file_name: common.vhd
    language: vhdl
    library: work
    entity_names:
  - file_name: clock_divider.vhd
    language: vhdl
    library: work
    entity_names:
      - clock_divider
  - file_name: tinymt32.vhd
    language: vhdl
    library: work
    entity_names:
      - tinymt32
  - file_name: random_generator.vhd
    language: vhdl
    library: work
    entity_names:
      - random_generator
  - file_name: pmodda3_controller.vhd
    language: vhdl
    library: work
    entity_names:
      - pmodda3_controller
  - file_name: papilio_wrapper.vhd
    language: vhdl
    library: work
    entity_names:
      - papilio_wrapper

test_files:
  - file_name: test_clock_divider.vhd
    entity_names:
      - test_clock_divider
  - file_name: test_tinymt32.vhd
    entity_names:
      - test_tinymt32
  - file_name: test_random_generator.vhd
    entity_names:
      - test_random_generator
  - file_name: test_papilio_wrapper.vhd
    entity_names:
      - test_papilio_wrapper

ucf_file: papilio.ucf

top_module: papilio_wrapper

part:
  device: xc6slx9
  package: tqg144
  speed: -2
